name: CMake on a single platform

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/tensorrt:23.09-py3

    steps:
    - uses: actions/checkout@v3

    - name: Pre-configure tzdata
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export TZ=America/Los_Angeles
        ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
        apt-get update
        apt-get install -y tzdata
        dpkg-reconfigure --frontend noninteractive tzdata

    - name: Install dependencies
      run: |
        apt-get install -y --no-install-recommends libopencv-dev cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}