# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install OpenCV
    - name: Install OpenCV
      run: sudo apt-get update && sudo apt-get install -y libopencv-dev

    # Install Eigen3
    - name: Install Eigen3
      run: sudo apt-get install -y libeigen3-dev

    # Install CUDA (Assuming you want the default version for Ubuntu)
    - name: Install CUDA
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit
        echo "/usr/local/cuda/lib64" >> $GITHUB_PATH
        echo "/usr/local/cuda/include" >> $GITHUB_PATH

    # Configure CMake
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Test
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
