name: CMake on a single platform

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]
    container:
      image: nvcr.io/nvidia/tensorrt:23.09-py3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache opencv dependencies
      id: cache-opencv
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/lib/libopencv*
          /usr/include/opencv4
        key: ${{ runner.os }}-opencv-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Cache eigen dependencies
      id: cache-eigen
      uses: actions/cache@v3
      with:
        path: /usr/include/eigen3
        key: ${{ runner.os }}-eigen-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Cache Boost dependencies
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: /usr/include/boost
        key: ${{ runner.os }}-boost-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Cache CMake build
      id: cache-cmake
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Pre-configure tzdata
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export TZ=America/Los_Angeles
        ln -fs /usr/share/zoneinfo/$TZ /etc/localtime
        apt-get update
        apt-get install -y tzdata
        dpkg-reconfigure --frontend noninteractive tzdata

    - name: Install dependencies
      if: steps.cache-opencv.outputs.cache-hit != 'true' || steps.cache-eigen.outputs.cache-hit != 'true'
      run: |
        apt-get install -y --no-install-recommends libopencv-dev cmake libeigen3-dev libboost-all-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}